version: "2.0"
services:
  nginx:
    build: "nginx"
    ports:
    - "80:80"
    depends_on:
    - jenkins
    - sonarqube

  jenkins:
    image: jenkinsci/blueocean
    environment:
    - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
    - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube
    command: -Dsonar.web.context=/sonarqube
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
    - sonarqube_data:/opt/sonarqube/data
    depends_on:
    - postgres

  postgres:
    image: postgres
    volumes:
    - postgre_data:/var/lib/postgresql
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

volumes:
  jenkins_home:
  sonarqube_data:
  postgre_data:

